import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset('titanic')
sns.displot(data=df,x='age',kde=False,bins=30,color='skyblue')
plt.title("Distribution of Age")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()
sns.kdeplot(data=df,x='age',fill=True, color='purple')
plt.title("Distribution of Age")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()
sns.kdeplot(data=df,x="age",fill=True,color='purple')
plt.title("Age Distribution with KDE")
plt.xlabel("Age")
plt.ylabel("Density")
plt.show()
avg_fare=df.groupby('pclass')['fare'].mean().reset_index()
sns.lineplot(data=avg_fare,x='pclass',y='fare',marker='o',color='green')
plt.title("average fare by passenger class")
plt.xlabel("passenger class") 
plt.ylabel("Average Fare")
plt.show()
sns.set_palette("Set1")
sns.scatterplot(data=df, x='age', y='fare', hue='survived', style='sex')
plt.title("Scatter Plot of Age vs Fare by Survival and Gender")
plt.xlabel("Age")
plt.ylabel("Fare")
plt.legend("Survived", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()